url: "http://thomasmason.us" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "thomasm1248" # the name of your site, e.g. ACME Corp.
description: My collection of stuff
